import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";
import { ToastProviders, Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "serverless-crm",
  description: "Generated by create-next-app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background font-sans antialiased">
        <ToastProviders>
          {children}
          <Toaster />
        </ToastProviders>
      </body>
    </html>
  );
}
